language: node_js

cache: yarn

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: true
    before_install:
      - docker pull mongo:4.0.0
      - docker images
    node_js:
      - "8"
      - "10"
    services:
      - docker
  - os: linux
    dist: trusty
    sudo: true
    before_install:
      - docker pull mongo:4.0.0
      - docker images
      - docker --version
    node_js:
      - "8"
      - "10"
    services:
      - docker
    - os: osx
    script: yarn unit

