language: node_js
node_js:
  - "8"
  - "10"
cache: yarn
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: false
  - os: linux
    dist: trusty
    sudo: false
  - os: osx
    scripts: yarn unit
before-install:
  - docker pull mongo:4.0.0
  - docker images
services:
  - docker
