language: node_js

cache: yarn

jobs:
  include:
  - stage: linux-full-build-node-8
    os: linux
    dist: xenial
    sudo: false
    node_js:
      - '8'
    services:
      - docker
  - stage: linux-full-build-node-8
    os: linux
    dist: trusty
    sudo: false
    node_js:
      - '8'
    services:
      - docker
  - stage: linux-full-build-node-10
    os: linux
    dist: xenial
    sudo: false
    node_js:
      - '10'
    services:
      - docker
  - stage: linux-full-build-node-10
    os: linux
    dist: trusty
    sudo: false
    node_js:
      - '10'
    services:
      - docker
  - stage: osx-no-int-test-build
    os: osx
    script: yarn unit
    node_js:
      - '8'
  - stage: osx-no-int-test-build
    os: osx
    script: yarn unit
    node_js:
      - '10'
