language: node_js
node_js:
  - "8"
  - "10"
cache: yarn
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: true
    before_install:
      - docker pull mongo:4.0.0
      - docker images
  - os: linux
    dist: trusty
    sudo: true
    before_install:
      - docker pull mongo:4.0.0
      - docker images
      - docker --version
  - os: osx
    script: yarn unit
services:
  - docker
