language: node_js
node_js:
  - "8"
  - "10"
cache: yarn
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: false
    before-install:
      - docker pull mongo:4.0.0
      - docker images
  - os: linux
    dist: trusty
    sudo: false
    before-install:
      - docker pull mongo:4.0.0
      - docker images
  - os: osx
    scripts: yarn unit
services:
  - docker
