language: node_js

cache: yarn

node_js:
  - "8"
  - "10"

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: true
    before_install:
      - docker pull mongo:4.0.0
      - docker images
    services:
      - docker
  - os: linux
    dist: trusty
    sudo: true
    before_install:
      - docker pull mongo:4.0.0
      - docker images
    services:
      - docker
  - os: osx
    script: yarn unit

