language: node_js

cache: yarn

jobs:
  include:
  - stage: linux-full-build-node-8
    os: linux
    dist: xenial
    sudo: true
    node:
      - '8'
    before_install:
      - docker pull mongo:4.0.0
      - docker images
    services:
      - docker
  - stage: linux-full-build-node-8
    os: linux
    dist: trusty
    sudo: true
    node:
      - '8'
    services:
      - docker
  - stage: linux-full-build-node-10
    os: linux
    dist: xenial
    sudo: true
    node:
      - '10'
    services:
      - docker
  - stage: linux-full-build-node-10
    os: linux
    dist: trusty
    sudo: true
    node:
      - '10'
    services:
      - docker
  - stage: osx-no-int-test-build
    os: osx
    script: yarn unit
    node:
      - '8'
      - '10'
    before_install:
      - echo 'osX -> disable before install'

before_install:
  - docker pull mongo:4.0.0
  - docker images
