parameters:
  name: ''  # defaults for any parameters that aren't specified
  vmImage: ''
  nodeVersion: ''

jobs:
- job: ${{ format('Build-{0}', parameters.name) }}
  displayName: ${{ format('Build on {0}', parameters.name) }}
  steps:
  - template: ./azure-step-template
  parameters:
    name: ${{parameters.name}}
    nodeVersion: ${{parameters.nodeVersion}}
